### ISSUE TITLE
monaco nerd fonts display not normal

### ISSUE THREAD

**Issue by taigacute** [Karmenzind/monaco-nerd-fonts#1]
## environment
mac os 10.13。6
## terminal
iterm 2
## Neovim 
neovim 0.3.4
## Problem
Is its height abnormal? How to solve it？ like this pic
![13](https://user-images.githubusercontent.com/41671631/54202473-132a3200-450b-11e9-8968-0860506379ab.png)
@Karmenzind  thanks

**Comment by Karmenzind** [comment]
No the height is ok.
Are you using the mono font?

I hate those triangles so I simply set `g:airline_left_sep` and `g:airline_right_sep` to `''`.

**Comment by taigacute** [comment]
@Karmenzind  maybe  i am macos。this is lightline。

**Comment by Karmenzind** [comment]
咦你base china
我意思是 等宽 也就是mono 和不等宽的字体 里面的图标显示效果是不一样的 你切换试一下
跟lightline和mac没关系

**Comment by taigacute** [comment]
@Karmenzind 2333333。我用的是mono。好像一直都有这个问题monaco  和作者说了。之前就有相关issue摆哪里很久了

**Comment by Karmenzind** [comment]
你换成不带mono的试试，应该会好一点。这个和monaco是没有关系的，nerd fonts用的都是同一套图形字符。就是给基础字体打了个补丁而已。

等等，你说的高度是指里面的图形吧？

**Comment by taigacute** [comment]
我试了好多monaco的nerd了 都不行。高度一直不对的说。。

**Comment by taigacute** [comment]
@Karmenzind  see [this issue](https://github.com/ryanoasis/nerd-fonts/issues/210)

**Comment by taigacute** [comment]
![231](https://user-images.githubusercontent.com/41671631/54415775-4d2c4b80-4738-11e9-84d6-279a9043ce92.png)

**Comment by Karmenzind** [comment]
好吧，这个我解决不了，早就放弃研究字体玄学了……
我用的是arch，终端alacritty，那个三角确实有点长，我一直以为它原本就是那样子

![2019-03-15-160259_959x224_scrot](https://user-images.githubusercontent.com/17923071/54417095-27a14100-473c-11e9-9891-8c770188af70.png)

**Comment by taigacute** [comment]
alacritty我也用。不过emoji颜色不正常。等待修复中。字体这个只能等作者了
