### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by guihkx** [Karmenzind/monaco-nerd-fonts#2]
I've been using your patched fonts for a long while on Arch Linux (and absolutely I love them, thanks). But a recent update of the `freetype2` package, from version `2.9.1` to version `2.10.0`, somehow "broke" your patched font. I've tried downgrading `freetype2` back to `2.9.1`, but Chromium completely breaks so unfortunately that's not an option... Anyway, here's a quick comparison:

Monaco Nerd Fonts (freetype2 2.9.1):

![terminal-freetype-old](https://user-images.githubusercontent.com/626206/54472047-eabb6580-47a0-11e9-80b1-76ebab321330.png)

Monaco Nerd Fonts (freetype2 2.10.0):

![terminal-freetype-new](https://user-images.githubusercontent.com/626206/54472050-0161bc80-47a1-11e9-856f-18d7ca888777.png)

As you can see from the screenshots above, the "line height" on version 2.10.0 seems substantially smaller when compared to version 2.9.1. So I was wondering if you could help me by telling me:

* Where did you get your `Monaco.{ttf,otf}` font?
* What options (arguments) did you use in `font-patcher` from nerd-fonts?

I just wanna see if building it myself using the latest freetype2 version will change anything.

Thanks a lot.

**Comment by Karmenzind** [comment]
Hi. I ran `pacman -Syu` one minite ago and it broke my font either, looked just like your second picture. And for now I have no idea how to fix it. Sorry.

Didn't remember where to get the original font. The options should simply be: `-c` (maybe with `--careful`). I never dig into how the patcher worked. Sorry for that again.

So if you found a solution, please let me know. Thank you very much.

**Comment by Karmenzind** [comment]
I searched `monaco` and got these repos:
https://github.com/todylu/monaco.ttf
https://github.com/cstrap/monaco-font
Hope it can help you.
I'll try to do the repatching at my leisure.

**Comment by guihkx** [comment]
Thanks for the links.

Yesterday I tried patching some monaco fonts I found on Github. The first one you linked didn't work for me, fontforge threw a bunch of errors I didn't know how to fix / ignore. Then I came across this [MonacoB font](https://github.com/vjpr/monaco-bold) (more specifically, the [MonacoBSemi variant](https://github.com/vjpr/monaco-bold/blob/master/MonacoBSemi/Monaco.otf)).

Then I created a PKGBUILD for it, based on a copy of [ttf-nerd-fonts-input](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ttf-nerd-fonts-input), applied the patch and I think it looks almost exactly like before!

Here's the PKGBUILD (beware, it downloads the entire nerd-fonts repo, it's about 2 GB):

```BASH
pkgname=ttf-nerd-fonts-monaco
pkgver=6.1
nerdfont_ver=2.0.0
pkgrel=3
pkgdesc='Monaco font patched with nerd-fonts'
arch=('any')
url='https://www.apple.com/'
license=('custom')
depends=('fontconfig' 'xorg-fonts-encodings' 'xorg-font-utils')
makedepends=('fontforge')
source=('Monaco.otf::https://github.com/vjpr/monaco-bold/raw/master/MonacoBSemi/Monaco.otf'
        "nerd-fonts-${nerdfont_ver}.tar.gz::https://github.com/ryanoasis/nerd-fonts/archive/v${nerdfont_ver}.tar.gz")
sha256sums=('2a1fd0a7c1e1e0cee42b5c96b642d6fde007c22d13c0b5c7731eb7732a817d4e'
            '0d5939042eff3b2d9b81ee2a871b3d2c046cbc6781f20ae87cdecfc1833e7bc8')

package() {
  mkdir -p ${pkgdir}/usr/share/fonts/monaco
  fontforge -script ${srcdir}/nerd-fonts-${nerdfont_ver}/font-patcher \
       --no-progressbars --careful \
       --complete --mono --outputdir \
       ${pkgdir}/usr/share/fonts/monaco ${srcdir}/Monaco.otf
  chmod 644 ${pkgdir}/usr/share/fonts/monaco/*
}
```

And here how it looks now on Konsole with freetype2 2.10.0:

![image](https://user-images.githubusercontent.com/626206/54490200-9abccb80-4892-11e9-9f91-86f8b6b91ace.png)

Although it already looks great (for me), I think I will try with some other Monaco fonts (like the second one you linked) when I have some free time. Thanks

**Comment by Karmenzind** [comment]
Good job. Thank you. 
I'll try your PKGBUILD later after getting home.
I read the patcher's script and found downloading https://github.com/ryanoasis/nerd-fonts/tree/master/src/glyphs will be fairly enough according to this line:
https://github.com/ryanoasis/nerd-fonts/blob/master/font-patcher#L761

You download the directory by:
```
# replace 'tree/master' with 'trunk'
svn checkout https://github.com/ryanoasis/nerd-fonts/trunk/src/glyphs
```
But I don't know how to write this into PKGBUILD.

**Comment by guihkx** [comment]
Thanks a lot for the tips! I've created a new PKGBUILD and submitted to the AUR:

https://aur.archlinux.org/packages/otf-nerd-fonts-monacob-mono/

I decided to go keep the MonacoB fonts, because every other one I tried didn't look as good. Let me know if it works for you.

You can also close this if you want.

**Comment by Karmenzind** [comment]
Glad to try it later. Too busy these days. 😫

**Comment by guixxx** [comment]
No problem, thanks for everything

**Comment by guihkx** [comment]
No problem, thanks for everything
