### ISSUE TITLE
There is a little question of position.

### ISSUE THREAD

**Issue by fintanchen** [Karmenzind/monaco-nerd-fonts#3]
I have been trying it today on macos and iTerm2. The font is awesome and worked well almost everywhere. But there is a little question of position. 
Here is the screenshot of patched font and the original font. As you can see, the arrow in patched font a little bit lower than the sign.

![image](https://user-images.githubusercontent.com/28680236/58062095-9f13a680-7bab-11e9-83f9-c0b3fc19a941.png)

If I switch to powershell with a powerline enabled theme, the arrow looks wired.
![image](https://user-images.githubusercontent.com/28680236/58062184-f74aa880-7bab-11e9-86f8-f695f6574f42.png)

If you have any suggestions, please tell me. Thank you very much.

**Comment by Karmenzind** [comment]
If you have checked the nerd font repository,  they have their own glyphs files for patching.  Maybe they just replaced the arrow glyphs, I guess.

 You can create an issue at their repository.  There are many questions there about the detail of the font.  I don't know much about this. Sorry.

**Comment by fintanchen** [comment]
yes, it is typo. I'm sorry about my poor English. I'm not a native English speaker.😅
Maybe I should patched the font by myself.
So I close this issue, and will give it a try.
