### ISSUE TITLE
Why it doesn't work in Gvim

### ISSUE THREAD

**Issue by devilyouwei** [Karmenzind/monaco-nerd-fonts#4]
I downloaded your font and it doesn't work on gnome-terminal, so I use font-patcher to create another, it works on ubuntu gnome-terminal.

But, the problem always breaks up on windows. It doesn't work both yours and mine.
I add this to windows/fonts/, it can be installed but can't be used by Gvim!
Gvim can't find this font. That's pretty confusing, do you know why?

**Comment by Karmenzind** [comment]
show me your font configration in vimrc or gvimrc

**Comment by devilyouwei** [comment]
I have added "Monaco Nerd Font Complete Mono Windows Compatible.otf" to c:/Windows/fonts

My _vimrc is
`
set guifont=Monaco_NF:h15:b
`
I checked the name of this Monaco font, windows show it is 'Monaco NF' and space is replaced by '_' in gvim

**Comment by devilyouwei** [comment]
When I use 'source $MYVIMRC'
It shows Error like: "Not effective font: guifont=Monaco_NF:h15:b"

**Comment by Karmenzind** [comment]
I don't have a Windows PC. There's nothing I can do to help you. Sorry for that.
I'll try to figure out your problem when I'm using Windows someday, but that might be quite late.

**Comment by devilyouwei** [comment]
Finally, I use another font for vim config NewRoman
