### ISSUE TITLE
why this font in windows shows "fi" to tel icon

### ISSUE THREAD

**Issue by jacquen** [Karmenzind/monaco-nerd-fonts#5]
Hi,

Thanks for hard work first.

I used this font on windows, it display any "fi" characters as telephone icon, any idea?

**Comment by Karmenzind** [comment]
https://github.com/ryanoasis/nerd-fonts/issues/254

Sorry I cannot help you with this.
This font is patched several years ago. Maybe you can try to build a new one. See https://github.com/ryanoasis/nerd-fonts .

**Comment by howin98** [comment]
i used fontforge to delete the refaction of "fl" and "fi", and it works well on Win10.

**Comment by gmr458** [comment]
> i used fontforge to delete the reflection of "fl" and "fi", and it works well on Win10.

Could you give me more specific instructions on how to solve this problem? Please.

**Comment by micaelviana** [comment]
> i used fontforge to delete the reflection of "fl" and "fi", and it works well on Win10.

How did you do this?

**Comment by rjorge99** [comment]
> > i used fontforge to delete the reflection of "fl" and "fi", and it works well on Win10.
> 
> How did you do this?

Hi, I just made some changes, if you want to use the font with out those problems.
https://github.com/rjorge99/MonacoNerdFontWindows

**Comment by micaelviana** [comment]
Thank you

**Comment by Finii** [comment]
Well, just use a more recent Nerd Fonts font-patcher, the `fl` bug has been fixed meanwhile.

**Comment by Karmenzind** [comment]
@Finii Thanks. It worked.
