### ISSUE TITLE
I can't install the font successfully

### ISSUE THREAD

**Issue by mouzaisibyl** [Karmenzind/monaco-nerd-fonts#7]
Thank you so much for tinkering with the Monaco font.
but when I put them in my /usr/share/fonts/myfonts/ and run 
```shell
sudo mkfontscale 
sudo mkfontdir 
sudo fc-cache -f
```
I still haven't found the monaco font.
I tried other fonts and can find it.

I am currently in Ubuntu20.04 .

**Comment by Karmenzind** [comment]
Please show me the result of  `fc-list | grep -i monaco`.
And you need to give more information (what, where and how) about "haven't found the monaco font". 
Applications treated fonts in different ways. Here is my alacritty font config:
![Uploading image.png…]()

**Comment by mouzaisibyl** [comment]
thanks for replying to me!
`fc-list | grep -i monaco`:
![monaco](https://user-images.githubusercontent.com/69446758/157502380-f20233ea-adf8-432b-8b45-6ddd42f92b44.png)

I opened my terminal configuration options to select fonts
![selectfont1](https://user-images.githubusercontent.com/69446758/157502962-47146a96-b352-4e2e-9217-e1c1cc57be29.png)

![selectfont2](https://user-images.githubusercontent.com/69446758/157502978-cf8a9933-23ce-4153-a99e-256e4f9abb2b.png)

**Comment by mouzaisibyl** [comment]
add:
I can't see your picture
![can't](https://user-images.githubusercontent.com/69446758/157514341-637c78f6-d796-4ba9-a905-f3372c573391.png)

**Comment by mouzaisibyl** [comment]
I tried alacritty and learned to configure the fonts and now he succeeded !!!
Thank you ! ! !

**Comment by Karmenzind** [comment]
抱歉回晚了。那你接着用alarcitty吧，这玩意儿挺快的
你图片这个是什么终端？我有空研究一下它为何不识别

**Comment by Karmenzind** [comment]
https://github.com/Karmenzind/dotfiles-and-scripts/blob/master/home_k/.config/alacritty/alacritty.yml
这个是我的alarcitty配置，可以参考一下

**Comment by mouzaisibyl** [comment]
哈哈哈谢谢你让我接触了alarcitty，让我的vim流畅了不少，谢谢你的字体和配置文件

**Comment by mouzaisibyl** [comment]
那个终端就Ubuntu20.04的原生终端

**Comment by Karmenzind** [comment]
不客气～
